#!/usr/bin/env python3
"""
gen_charrss_constants.py -- OFFLINE generator for the baked character-RSS tables.

Emits the CVP (closest-vector) reconstruction tables used by charrss.js: an
LLL-reduced lattice basis plus its float Gram-Schmidt data. The LLL reduction is
slow + exact-rational and must NEVER run in the browser; this script runs it once,
gates it behind a correctness self-test (Schnorr-Euchner enumeration over many
random seeds), and writes an ES module the runtime imports.

The runtime algorithm is a direct truncated-LCG / Hidden-Number-Problem solve
that reconstructs the seed from 9 characters with no brute-force residual.
See RSS_IMPLEMENTATION.md.

Usage:
    python3 tools/gen_charrss_constants.py [--chars 9] [--trials 5000] [--out PATH]

Default output: docs/js/charrss_constants.js
"""
import argparse
import os
import sys
import time
from datetime import date

# Import the prototype/oracle as a library (repo root is parent of this file's dir).
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import charrss as cr  # noqa: E402


def build(num_chars):
    t0 = time.time()
    R = cr.cvp_basis(num_chars)
    prep = cr.cvp_prepare(R)
    return prep, time.time() - t0



def js_ints(v):
    return "[" + ",".join(str(x) for x in v) + "]"


def js_floats(v):
    return "[" + ",".join(repr(float(x)) for x in v) + "]"


def emit_js(prep, num_chars, stats, gen_secs, trials, out_path):
    found, not_found, false_pos, multi = stats
    n = prep["n"]
    lines = [
        "// AUTO-GENERATED by tools/gen_charrss_constants.py -- DO NOT HAND-EDIT.",
        "// Baked LLL basis + float Gram-Schmidt data for the client-side character RSS",
        "// (direct truncated-LCG / Hidden-Number-Problem closest-vector reconstruction).",
        "// Regenerate with: python3 tools/gen_charrss_constants.py --chars %d" % num_chars,
        "//",
        "// Provenance:",
        "//   generated:    %s" % date.today().isoformat(),
        "//   first-search: %d characters (lattice dimension n = %d)" % (num_chars, n),
        "//   gen time:     %.0fs (LLL, exact rational; offline only)" % gen_secs,
        "//   self-test:    %d/%d found, %d not-found, %d false-pos, %d multi-match" % (
            found, trials, not_found, false_pos, multi),
        "//   lcg:          next(s)=(214013*s+2531011) mod 2^32; char step = next^2; bound=25",
        "",
        "// Per-length table. The runtime is keyed by character-sequence length, so",
        "// additional lengths can be baked here later without any code change.",
        "//   basis  : LLL-reduced lattice basis R (n x n integers).",
        "//   gsStar : Gram-Schmidt vectors b*_i (n x n floats).",
        "//   gsDen  : squared norms ||b*_i||^2 (n floats).",
        "//   mu     : mu[j][i] = <R[j],b*_i> / ||b*_i||^2 (n x n floats).",
        "//   r0     : column 0 of R (anchor-seed coordinate; n integers).",
        "export const CHARRSS_TABLES = {",
        "  %d: {" % num_chars,
        "    n: %d," % n,
        "    basis: [",
    ]
    for row in prep["basis"]:
        lines.append("      %s," % js_ints(row))
    lines.append("    ],")
    lines.append("    gsStar: [")
    for row in prep["gsStar"]:
        lines.append("      %s," % js_floats(row))
    lines.append("    ],")
    lines.append("    gsDen: %s," % js_floats(prep["gsDen"]))
    lines.append("    mu: [")
    for row in prep["mu"]:
        lines.append("      %s," % js_floats(row))
    lines.append("    ],")
    lines.append("    r0: %s," % js_ints(prep["r0"]))
    lines.append("  },")
    lines.append("};")
    lines.append("")
    lines.append("export const FIRST_SEARCH_CHARS = %d;" % num_chars)
    lines.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--chars", type=int, default=9, help="first-search length (>=8)")
    ap.add_argument("--trials", type=int, default=5000, help="self-test seed count")
    ap.add_argument("--out", default=None, help="output .js path")
    args = ap.parse_args()

    if args.chars < 8:
        print("ERROR: %d chars is below the info-theoretic margin for reconstruction "
              "(need >=8; 9 is the recommended/validated length). Aborting." % args.chars,
              file=sys.stderr)
        return 2
    if args.chars < 9:
        print("WARNING: 8 chars is near the reconstruction cliff (~95%% in profiling); "
              "9 is the validated length. Continuing -- the self-test gate decides.",
              file=sys.stderr)

    out = args.out or os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "docs", "js", "charrss_constants.js")

    print("Generating %d-char CVP lattice (n=%d) via LLL..." % (args.chars, args.chars))
    prep, gen_secs = build(args.chars)
    print("  reduced in %.0fs; validating over %d seeds..." % (gen_secs, args.trials))
    v = cr.validate_cvp(prep, args.chars, args.trials)
    found, not_found, false_pos, multi = v["found"], v["not_found"], v["false_pos"], v["multi"]
    stats = (found, not_found, false_pos, multi)
    print("  self-test: %d/%d found, %d not-found, %d false-pos, %d multi-match"
          % (found, args.trials, not_found, false_pos, multi))

    if found != args.trials or not_found != 0 or false_pos != 0:
        print("GATE FAILED: reconstruction not 100%% / had false positives. "
              "NOT writing output.", file=sys.stderr)
        return 1

    emit_js(prep, args.chars, stats, gen_secs, args.trials, out)
    print("  wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
